Repository yalla-coop/cost-of-living-support, pull requests merged in 2022-11, with the labels that each got.

#1 0 update packages
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/ErrorBoundary.js
  client/src/components/Button/index.js
  client/src/components/GoBack/index.js
  client/src/components/Inputs/ImageUpload/index.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Route/Redirect.js
  client/src/components/Route/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/ScrollToTop.js
  client/src/index.js
  client/src/pages/Admin/CreateOrganisationDetails/SecondStep.js
  client/src/pages/Admin/CreateOrganisationDetails/index.js
  client/src/pages/Admin/CreateUniqueLink/index.js
  client/src/pages/Admin/ManageSteps/DragDrop.js
  client/src/pages/Admin/Welcome/index.js
  client/src/pages/Admin/index.js
  client/src/pages/Home/index.js
  client/src/pages/Login/index.js
  client/src/pages/ResetPassword/index.js
  client/src/pages/Signup/index.js
  client/src/pages/Step/index.js
  client/src/validation/custom-functions.js
  client/src/validation/fields.js
  client/src/validation/schemas/signup.js
  client/yarn.lock
  package-lock.json
  package.json
Labels: awaiting-review

#2 update git ignore files
  .gitignore
  client/.gitignore
Labels: awaiting-review

#71 54 col landing page
  client/.storybook/main.js
  client/package-lock.json
  client/src/api-calls/index.js
  client/src/api-calls/sections.js
  client/src/components/Cards/Cards.stories.js
  client/src/components/Cards/SectionCard/index.js
  client/src/components/Cards/SectionCard/style.js
  client/src/components/Cards/index.js
  client/src/components/Icon/icons/Basket.js
  client/src/components/Icon/icons/Bill.js
  client/src/components/Icon/icons/Calculator.js
  client/src/components/Icon/icons/House.js
  client/src/components/Icon/icons/MoneyBag.js
  client/src/components/Icon/index.js
  client/src/components/Layout/General/style.js
  client/src/components/TextWithIcon/TextWithIcon.stories.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TextWithIcon/style.js
  client/src/components/Typography/index.js
  client/src/components/assets/Logo.png
  client/src/pages/Home/LandingContent.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  client/src/theme/colors.js
  package-lock.json
  package.json
Labels: awaiting-review

#73 72 components markdown editor header
  client/package-lock.json
  client/package.json
  client/src/components/MDEditor/MDEditor.stories.js
  client/src/components/MDEditor/index.js
  client/src/components/MDEditor/style.js
  client/src/components/Markdown/Markdown.stories.js
  client/src/components/Markdown/index.js
  client/src/components/PageHeader/PageHeader.stories.js
  client/src/components/PageHeader/index.js
  client/src/components/PageHeader/style.js
Labels: awaiting-review

#75 72 update typograph and colors
  client/src/components/Inputs/Textarea/style.js
  client/src/components/ReCaptcha/index.js
  client/src/components/Typography/Typography.stories.js
  client/src/components/Typography/index.js
  client/src/pages/Signup/index.js
  client/src/stories/colors.stories.js
  client/src/theme/colors.js
Labels: awaiting-review

#76 77 setup testing
  README.md
  client/babel.config.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.spec.tsx
  client/src/App.test.js
  client/src/__snapshots__/App.spec.tsx.snap
  client/src/components/Icon/icons/Flag.js
  client/src/react-app-env.d.ts
  client/tsconfig.json
  package-lock.json
  package.json
  server/babel.config.js
  server/config/test.spec.js
  server/jest.config.js
  server/modules/media/model/find.spec.js
  server/package-lock.json
  server/package.json
  server/test/setEnvVars.js
  tsconfig.json
Labels: requested changes

#84 create landing page backend
  client/src/App.js
  client/src/api-calls/sections.js
  client/src/components/Button/index.js
  client/src/components/Button/style.js
  client/src/components/Cards/Cards.stories.js
  client/src/components/Cards/SectionCard/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  server/database/build-tables.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/organisations-sections-orders.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data-prod/users.js
  server/database/dummy-data/index.js
  server/database/dummy-data/organisations-sections-orders.js
  server/database/dummy-data/organisations.js
  server/database/dummy-data/users.js
  server/database/models/index.js
  server/modules/section/controllers/get-sections.js
  server/modules/section/model/find.js
  server/modules/section/use-cases/get-sections.js
Labels: awaiting-review

#85 update general layout
  client/src/App.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Layout/GeneralPaddingSection/index.js
  client/src/components/Layout/GeneralPaddingSection/style.js
  client/src/components/Layout/Step/index.js
  client/src/components/Layout/Step/style.js
  client/src/components/Layout/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  client/src/pages/Section/index.js
  client/src/pages/Section/style.js
  client/src/pages/Step/index.js
  client/src/pages/Step/style.js
  client/src/pages/index.js
Labels: awaiting-review

#86 46 paying for housing page
  client/src/App.js
  client/src/api-calls/sections.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/GeneralPaddingSection/style.js
  client/src/components/PageHeader/style.js
  client/src/components/Route/index.js
  client/src/pages/Home/index.js
  client/src/pages/SubSections/index.js
  client/src/pages/SubSections/style.js
  client/src/pages/index.js
  server/database/dummy-data-prod/sections.js
  server/modules/section/controllers/get-sub-sections.js
  server/modules/section/controllers/index.js
  server/modules/section/model/find.js
  server/modules/section/use-cases/get-sections.js
  server/modules/section/use-cases/get-sub-sections.js
  server/modules/section/use-cases/index.js
Labels: awaiting-review

#89 42 login page
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Layout/SplitScreen/index.js
  client/src/components/Typography/index.js
  client/src/pages/Login/index.js
Labels: awaiting-review

#82 72 buttons section
  client/src/components/ButtonsSection/ButtonsSection.stories.js
  client/src/components/ButtonsSection/DragDrop.js
  client/src/components/ButtonsSection/SingleButton.js
  client/src/components/ButtonsSection/index.js
  client/src/components/ButtonsSection/style.js
  client/src/components/Icon/icons/Edit.js
  client/src/components/Icon/icons/Hide.js
  client/src/components/Icon/icons/Menu2.js
  client/src/components/Icon/index.js
  client/src/components/TextWithIcon/index.js
Labels: awaiting-review

#90 create content pages
  client/src/App.js
  client/src/api-calls/sections.js
  client/src/components/Cards/Cards.stories.js
  client/src/components/Cards/SectionCard/index.js
  client/src/components/Cards/Tips/index.js
  client/src/components/Cards/Topic/index.js
  client/src/components/Cards/Topic/style.js
  client/src/components/GoBack/index.js
  client/src/components/HelpfulResources/index.js
  client/src/components/Layout/GeneralPaddingSection/style.js
  client/src/components/Layout/SplitScreen/index.js
  client/src/constants/benefit-calculator.js
  client/src/constants/content-colors.js
  client/src/constants/index.js
  client/src/constants/nav-routes.js
  client/src/constants/resources.js
  client/src/context/public-org.js
  client/src/pages/Admin/CreateOrganisationDetails/index.js
  client/src/pages/Admin/EditDetails/index.js
  client/src/pages/OrgPublic/Home/LandingContent.js
  client/src/pages/OrgPublic/Home/index.js
  client/src/pages/OrgPublic/Home/style.js
  client/src/pages/OrgPublic/MentalHeath/index.js
  client/src/pages/OrgPublic/MentalHeath/style.js
  client/src/pages/OrgPublic/Section/index.js
  client/src/pages/OrgPublic/Section/style.js
  client/src/pages/OrgPublic/Section/useTopics.js
  client/src/pages/OrgPublic/SubSections/index.js
  client/src/pages/OrgPublic/SubSections/style.js
  client/src/pages/Section/index.js
  client/src/pages/Section/style.js
  client/src/pages/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/create-organisation-details.js
  client/src/validation/schemas/edit-details.js
  server/constants/app-links.js
  server/database/build-tables.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data-prod/prod-data.js
  server/database/dummy-data-prod/topics.js
  server/database/dummy-data/index.js
  server/database/dummy-data/organisations-resources.js
  server/database/dummy-data/organisations.js
  server/database/models/index.js
  server/database/models/organisations-resources/index.js
  server/database/models/organisations-resources/schema.sql
  server/database/models/organisations/schema.sql
  server/modules/organisation/controllers/get-organisation.js
  server/modules/organisation/controllers/update-organisation.js
  server/modules/organisation/model/find.js
  server/modules/organisation/model/update.js
  server/modules/organisation/use-cases/update-organisation.js
  server/modules/section/controllers/get-topics-by-section-id.js
  server/modules/section/controllers/index.js
  server/modules/section/model/find.js
  server/modules/section/use-cases/get-section.js
  server/modules/section/use-cases/get-topics-by-section-id.js
  server/modules/section/use-cases/index.js
  server/package-lock.json
Labels: awaiting-review

#77 Language frontend
  client/src/components/Icon/icons/Accessibility.js
  client/src/components/Icon/icons/Arabic.js
  client/src/components/Icon/icons/BackArrow.js
  client/src/components/Icon/icons/BackArrowRTL.js
  client/src/components/Icon/icons/English.js
  client/src/components/Icon/icons/French.js
  client/src/components/Icon/icons/German.js
  client/src/components/Icon/icons/Hindi.js
  client/src/components/Icon/icons/Italian.js
  client/src/components/Icon/icons/Polish.js
  client/src/components/Icon/icons/Portuguese.js
  client/src/components/Icon/icons/Russian.js
  client/src/components/Icon/icons/Search.js
  client/src/components/Icon/icons/Spanish.js
  client/src/components/Icon/icons/TextSize.js
  client/src/components/Icon/icons/Urdu.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Language/Language.stories.js
  client/src/components/Language/LanguageBar/LanguageBar.stories.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/LanguageBar/style.js
  client/src/components/Language/LanguageSelector/LanguageSelector.stories.js
  client/src/components/Language/LanguageSelector/index.js
  client/src/components/Language/LanguageSelector/style.js
  client/src/components/Language/index.js
  client/src/components/Language/style.js
  client/src/components/Layout/General/index.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TextWithIcon/style.js
  client/src/constants/data-types.js
  client/src/theme/borders.js
  client/src/theme/index.js
Labels: awaiting-review, CoL + UC

#91 48 budgeting page
  client/src/App.js
  client/src/components/Cards/Tips/SingleTip.js
  client/src/components/Cards/Tips/index.js
  client/src/components/Cards/Tips/style.js
  client/src/components/Cards/index.js
  client/src/components/index.js
  client/src/constants/resources.js
  client/src/pages/OrgPublic/Budgeting/index.js
  client/src/pages/OrgPublic/Budgeting/style.js
  client/src/pages/index.js
  client/src/theme/colors.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data/organisations-resources.js
  server/database/dummy-data/organisations.js
Labels: awaiting-review

#99 create customise links page
  client/package-lock.json
  client/package.json
  client/src/api-calls/organisations.js
  client/src/components/Icon/icons/Refresh.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Inputs/Inputs.stories.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Navbar/style.js
  client/src/constants/nav-routes.js
  client/src/constants/resources.js
  client/src/constants/translations/english/menu-items.js
  client/src/context/admin-org.js
  client/src/pages/Admin/CustomiseResources/index.js
  client/src/pages/Admin/CustomiseResources/style.js
  client/src/pages/Admin/index.js
  client/src/validation/custom-functions.js
  client/src/validation/fields.js
  client/src/validation/schemas/customise-resources.js
  client/src/validation/schemas/index.js
  server/database/models/organisations-resources/schema.sql
  server/modules/organisation/controllers/index.js
  server/modules/organisation/controllers/update-resources.js
  server/modules/organisation/model/find.js
  server/modules/organisation/model/remove.js
  server/modules/organisation/model/update.js
  server/modules/organisation/use-cases/index.js
  server/modules/organisation/use-cases/update-resources.js
Labels: awaiting-review

#97 44 org account creation
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/Checkbox/index.js
  client/src/components/Inputs/Checkbox/style.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Layout/SplitScreen/style.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Admin/SuccessSignup/index.js
  client/src/pages/Admin/SuccessSignup/style.js
  client/src/pages/Admin/Welcome/Welcome1.js
  client/src/pages/Admin/Welcome/Welcome2.js
  client/src/pages/Admin/Welcome/index.js
  client/src/pages/Admin/Welcome/style.js
  client/src/pages/Admin/index.js
  client/src/pages/Login/index.js
  client/src/pages/Signup/index.js
Labels: awaiting-review, CoL + UC

#101 43 org dashboard structure
  client/src/api-calls/organisations.js
  client/src/components/Cards/Tips/SingleTip.js
  client/src/components/Cards/Tips/index.js
  client/src/components/Cards/Tips/style.js
  client/src/components/HelpButton/AdminHelp.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/components/Layout/Dashboard/index.js
  client/src/components/Layout/Dashboard/style.js
  client/src/components/Modal/style.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Navbar/index.js
  client/src/components/Navbar/style.js
  client/src/components/TextWithIcon/style.js
  client/src/constants/nav-routes.js
  client/src/constants/translations/english/menu-items.js
  client/src/context/admin-org.js
  client/src/pages/Admin/Dashboard/DashboardLinks.js
  client/src/pages/Admin/Dashboard/PendingDashboard.js
  client/src/pages/Admin/Dashboard/index.js
  client/src/pages/Admin/Dashboard/style.js
  client/src/pages/Admin/index.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data/organisations.js
  server/database/init/types.sql
  server/database/models/organisations/schema.sql
  server/modules/organisation/controllers/get-organisations.js
  server/modules/organisation/controllers/index.js
  server/modules/organisation/model/find.js
  server/modules/organisation/use-cases/get-organisations.js
  server/modules/organisation/use-cases/index.js
  server/modules/user/model/find.js
Labels: CoL + UC, approve

#102 Edit contact details
  client/src/components/Inputs/Dropdown/style.js
  client/src/constants/data-types.js
  client/src/constants/translations/english/index.js
  client/src/pages/Admin/EditDetails/index.js
  server/constants/data-type.js
  server/modules/organisation/controllers/update-organisation.js
  server/modules/organisation/model/update.js
  server/modules/organisation/use-cases/update-organisation.js
  server/modules/user/model/update.js
Labels: awaiting-review

#108 Add increase font size functionality
  client/src/App.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/ImageUpload/style.js
  client/src/components/Inputs/Textarea/style.js
  client/src/components/Inputs/style.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/PageHeader/index.js
  client/src/components/PageHeader/style.js
  client/src/components/TextWithIcon/style.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/context/accessibility.js
  client/src/pages/Accessibility/index.js
  client/src/pages/Accessibility/style.js
  client/src/pages/Login/index.js
  client/src/pages/OrgPublic/Home/style.js
  client/src/pages/index.js
Labels: awaiting-review

#104 add social banner
  client/package.json
  client/src/App.js
  client/src/components/Layout/General/index.js
  client/src/components/SocialBanner/SocialBanner.stories.js
  client/src/components/SocialBanner/index.js
  client/src/components/SocialBanner/style.js
  client/src/components/assets/Copy.svg
  client/src/components/assets/Email.svg
  client/src/components/assets/Facebook.svg
  client/src/components/assets/Whatsapp.svg
  client/src/context/public-org.js
  client/src/pages/OrgPublic/Budgeting/index.js
  client/src/pages/OrgPublic/MentalHeath/index.js
  client/src/pages/OrgPublic/Section/index.js
  client/src/pages/OrgPublic/SubSections/index.js
Labels: approve, conflict

#112 remove duplicate pages from the app
  client/src/App.js
Labels: awaiting-review

#100 I18next Frontend and Backend implementation
  client/package.json
  client/public/translate.json
  client/src/App.js
  client/src/api-calls/index.js
  client/src/api-calls/sections.js
  client/src/api-calls/translations.js
  client/src/components/Cards/Tips/index.js
  client/src/components/HelpButton/index.js
  client/src/components/Icon/icons/German.js
  client/src/components/Icon/icons/Urdu.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/LanguageSelector/index.js
  client/src/components/Layout/General/index.js
  client/src/components/Route/index.js
  client/src/constants/common.js
  client/src/constants/data-types.js
  client/src/constants/index.js
  client/src/context/common.js
  client/src/helpers/index.js
  client/src/helpers/use-language.js
  client/src/i18n.js
  client/src/index.js
  client/src/pages/OrgPublic/Home/LandingContent.js
  client/src/pages/OrgPublic/Home/index.js
  client/src/pages/OrgPublic/Section/index.js
  client/src/pages/OrgPublic/Section/useTopics.js
  client/src/pages/Section/index.js
  client/src/pages/Section/style.js
  client/src/pages/Section/useTopics.js
  server/api/index.js
  server/constants/data-type.js
  server/database/build-tables.js
  server/database/dummy-data-prod/common-i18n.js
  server/database/dummy-data-prod/common.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/organisations-resources.js
  server/database/dummy-data-prod/topics-i18n.js
  server/database/dummy-data-prod/topics.js
  server/database/dummy-data/index.js
  server/database/init/types.sql
  server/database/models/common-i18n/index.js
  server/database/models/common-i18n/schema.sql
  server/database/models/common/index.js
  server/database/models/common/schema.sql
  server/database/models/index.js
  server/database/models/organisations-resources/schema.sql
  server/database/models/topics-i18n/index.js
  server/database/models/topics-i18n/schema.sql
  server/modules/index.js
  server/modules/section/controllers/get-topics-by-section-id.js
  server/modules/section/model/find.js
  server/modules/section/use-cases/get-topics-by-section-id.js
  server/modules/translations/controllers/get-common.js
  server/modules/translations/controllers/index.js
  server/modules/translations/index.js
  server/modules/translations/model/find.js
  server/modules/translations/model/index.js
  server/modules/translations/use-cases/get-common.js
  server/modules/translations/use-cases/index.js
Labels: awaiting-review

#114 Dynamic language translation
  client/src/api-calls/translations.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/LanguageSelector/index.js
  client/src/helpers/use-language.js
  client/src/i18n.js
  client/src/index.js
  client/src/pages/Admin/Organisations/UserRow.js
  client/src/pages/OrgPublic/Section/index.js
  client/src/pages/OrgPublic/Section/useTopics.js
  client/src/pages/Section/index.js
  client/src/pages/Section/style.js
  client/src/pages/Section/useTopics.js
  server/config/aws.js
  server/database/dummy-data/index.js
  server/modules/section/model/create.js
  server/modules/section/use-cases/get-topics-by-section-id.js
  server/modules/translations/model/create.js
  server/modules/translations/model/index.js
  server/modules/translations/use-cases/get-common.js
  server/package.json
  server/services/translation/translate-content.js
  server/services/translation/translation-api.js
Labels: awaiting-review

#111 51 accessibility features
  client/src/App.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/index.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Modal/style.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/context/accessibility.js
  client/src/pages/Accessibility/OverlayColor.js
  client/src/pages/Accessibility/index.js
  client/src/pages/Accessibility/style.js
  client/src/theme/accessability-style.js
  client/src/theme/global-style.js
  client/src/theme/index.js
Labels: awaiting-review, CoL + UC
