Repository yalla-coop/cost-of-living-support, pull requests merged in 2022-12, with the labels that each got.

#109 create reject org page
  client/src/api-calls/organisations.js
  client/src/constants/nav-routes.js
  client/src/pages/Admin/ConfirmRejection/index.js
  client/src/pages/Admin/ConfirmRejection/style.js
  client/src/pages/Admin/Organisations/UserRow.js
  client/src/pages/Admin/Organisations/index.js
  client/src/pages/Admin/index.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/reject-organisation.js
  server/modules/organisation/controllers/update-organisation-status.js
  server/modules/organisation/use-cases/update-organisation-status.js
  server/package-lock.json
  server/services/mailing/templates/index.js
  server/services/mailing/templates/templates-constants.js
Labels: CoL + UC, approve

#121 Front-end translations
  client/src/components/GoBack/index.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpfulResources/index.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/LanguageSelector/index.js
  client/src/components/SocialBanner/index.js
  client/src/components/StillNeedHelp/index.js
  client/src/constants/common.js
  client/src/helpers/use-language.js
  client/src/i18n.js
  client/src/pages/Accessibility/OverlayColor.js
  client/src/pages/Accessibility/index.js
  client/src/pages/OrgPublic/Budgeting/index.js
  client/src/pages/OrgPublic/Home/index.js
  client/src/pages/OrgPublic/MentalHeath/index.js
  client/src/pages/OrgPublic/Section/index.js
  client/src/pages/OrgPublic/Section/useTopics.js
  client/src/pages/OrgPublic/SubSections/index.js
  server/database/dummy-data-prod/common.js
Labels: awaiting-review

#116 36 org add update content main view - front end and back end
  client/package.json
  client/src/api-calls/sections.js
  client/src/components/ButtonsSection/DragDrop.js
  client/src/components/ButtonsSection/SingleButton.js
  client/src/components/ButtonsSection/index.js
  client/src/components/ButtonsSection/style.js
  client/src/components/index.js
  client/src/pages/Admin/EditContent/UnderReview.js
  client/src/pages/Admin/EditContent/index.js
  client/src/pages/OrgPublic/Home/index.js
  server/modules/organisation/use-cases/update-organisation-status.js
  server/modules/section/controllers/index.js
  server/modules/section/controllers/update-sections-order.js
  server/modules/section/model/create.js
  server/modules/section/model/find.js
  server/modules/section/model/update.js
  server/modules/section/use-cases/get-sections.js
  server/modules/section/use-cases/index.js
  server/modules/section/use-cases/update-sections-order.js
Labels: awaiting-review

#125 33 fix update brand colors
  client/src/components/Button/style.js
  client/src/components/ButtonsSection/DragDrop.js
  client/src/components/ButtonsSection/SingleButton.js
  client/src/components/ButtonsSection/style.js
  client/src/components/Cards/SectionCard/style.js
  client/src/components/Cards/Tips/SingleTip.js
  client/src/components/Cards/Tips/index.js
  client/src/components/GoBack/index.js
  client/src/components/HelpButton/AdminHelp.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/components/HelpfulResources/index.js
  client/src/components/Inputs/Checkbox/style.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/InputArray/index.js
  client/src/components/Inputs/InputCMS/index.js
  client/src/components/Language/style.js
  client/src/components/Layout/Dashboard/style.js
  client/src/components/Layout/SplitScreen/style.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.js
  client/src/components/Navbar/index.js
  client/src/components/PageHeader/PageHeader.stories.js
  client/src/components/PageHeader/index.js
  client/src/components/PageHeader/style.js
  client/src/components/Steps/index.js
  client/src/components/StillNeedHelp/index.js
  client/src/components/TopicForm/TipInput.js
  client/src/components/TopicForm/TopicSectionForm.stories.js
  client/src/components/TopicForm/style.js
  client/src/components/TopicFormWithResources/index.js
  client/src/constants/content-colors.js
  client/src/context/public-org.js
  client/src/helpers/set-color-variations.js
  client/src/helpers/update-gradients.js
  client/src/pages/Admin/Changes/index.js
  client/src/pages/Admin/CreateUniqueLink/Success.js
  client/src/pages/Admin/Customise/index.js
  client/src/pages/Admin/Dashboard/DashboardLinks.js
  client/src/pages/Admin/Dashboard/PendingDashboard.js
  client/src/pages/Admin/Dashboard/index.js
  client/src/pages/Admin/ManageSteps/style.js
  client/src/pages/Admin/StepForm/ThingsYouWillNeed.js
  client/src/pages/Admin/StepForm/WhatYouWillNeedToKnow.js
  client/src/pages/Admin/Welcome/index.js
  client/src/pages/Login/index.js
  client/src/pages/OrgPublic/Budgeting/index.js
  client/src/pages/OrgPublic/Budgeting/style.js
  client/src/pages/OrgPublic/Home/LandingContent.js
  client/src/pages/OrgPublic/Home/index.js
  client/src/pages/OrgPublic/Home/style.js
  client/src/pages/OrgPublic/MentalHeath/index.js
  client/src/pages/OrgPublic/SubSections/index.js
  client/src/theme/borders.js
  client/src/theme/colors.js
  client/src/validation/fields.js
  client/src/validation/schemas/customise.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data/organisations.js
Labels: awaiting-review

#120 Add email templates details
  server/modules/organisation/use-cases/update-organisation-status.js
  server/modules/organisation/use-cases/update-organisation.js
  server/modules/section/use-cases/create-section.js
  server/modules/user/use-cases/reset-password-link.js
  server/modules/user/use-cases/signup.js
  server/services/mailing/templates/index.js
  server/services/mailing/templates/templates-constants.js
Labels: CoL + UC, approve

#126 Fix missing translations & add back arrow
  client/src/App.js
  client/src/components/Cards/Checklist/index.js
  client/src/components/Cards/Topic/index.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/InputCMS/index.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/TopicFormWithResources/TopicForm.js
  client/src/constants/common.js
  client/src/pages/Accessibility/OverlayColor.js
  server/database/dummy-data-prod/common.js
Labels: awaiting-review

#127 create approve section page
  client/src/api-calls/sections.js
  client/src/constants/nav-routes.js
  client/src/pages/Admin/ConfirmRejectSection/index.js
  client/src/pages/Admin/ConfirmRejectSection/style.js
  client/src/pages/Admin/ContentReview/ContentRow.js
  client/src/pages/Admin/ContentReview/index.js
  client/src/pages/Admin/ContentReview/style.js
  client/src/pages/Admin/EditContent/ContentSection.js
  client/src/pages/Admin/EditContent/index.js
  client/src/pages/Admin/SectionForm/index.js
  client/src/pages/Admin/index.js
  server/constants/data-type.js
  server/modules/organisation/model/find.js
  server/modules/organisation/use-cases/update-organisation-status.js
  server/modules/section/controllers/get-awaiting-review-sections.js
  server/modules/section/controllers/index.js
  server/modules/section/controllers/update-section-status.js
  server/modules/section/controllers/update-section.js
  server/modules/section/model/find.js
  server/modules/section/model/update.js
  server/modules/section/use-cases/get-awaiting-review-sections.js
  server/modules/section/use-cases/index.js
  server/modules/section/use-cases/update-section-status.js
  server/modules/section/use-cases/update-section.js
  server/services/mailing/templates/index.js
Labels: awaiting-review

#124 handle language direction
  client/src/App.js
  client/src/components/ButtonsSection/SingleButton.js
  client/src/components/Cards/Checklist/index.js
  client/src/components/Cards/Topic/index.js
  client/src/components/HelpButton/AdminHelp.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Inputs/InputArray/index.js
  client/src/components/Inputs/InputCMS/index.js
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Language/LanguageSelector/index.js
  client/src/components/PageHeader/style.js
  client/src/components/SocialBanner/index.js
  client/src/components/SocialBanner/style.js
  client/src/components/Steps/index.js
  client/src/components/TextWithIcon/TextWithIcon.stories.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TopicForm/TopicSectionForm.stories.js
  client/src/components/TopicFormWithResources/ResourcesSection.js
  client/src/components/TopicFormWithResources/TopicForm.js
  client/src/components/TopicFormWithResources/TopicSectionForm.stories.js
  client/src/components/TopicFormWithResources/index.js
  client/src/components/Typography/index.js
  client/src/context/common.js
  client/src/helpers/set-margin.js
  client/src/pages/Accessibility/style.js
  client/src/pages/Admin/Changes/index.js
  client/src/pages/Admin/CreateUniqueLink/Success.js
  client/src/pages/Admin/Dashboard/DashboardLinks.js
  client/src/pages/Admin/Dashboard/PendingDashboard.js
  client/src/pages/Admin/Dashboard/index.js
  client/src/pages/Admin/EditDetails/index.js
  client/src/pages/Admin/SectionForm/index.js
  client/src/pages/Admin/StepForm/ThingsYouWillNeed.js
  client/src/pages/Admin/StepForm/WhatYouWillNeedToKnow.js
  client/src/pages/Admin/Welcome/index.js
  client/src/pages/Login/index.js
  client/src/pages/OrgPublic/Home/index.js
  client/src/pages/OrgPublic/Home/style.js
  client/src/pages/OrgPublic/SubSections/index.js
  server/database/dummy-data-prod/common-i18n.js
  server/helpers/index.js
  server/helpers/remove-nulls-and-empty-arrays-and-objects.js
  server/modules/section/use-cases/get-section.js
  server/services/translation/translation-api.js
Labels: CoL + UC, approve

#128 117 admin implement markdown for tips
  client/src/components/Cards/Tips/SingleTip.js
  client/src/components/MDEditor/index.js
  client/src/components/MDEditor/style.js
  client/src/components/Markdown/index.js
  client/src/components/Markdown/style.js
  client/src/components/PageHeader/style.js
  client/src/components/TopicFormWithResources/TipInput.js
  client/src/components/Typography/index.js
  client/src/pages/Admin/SectionForm/index.js
  server/database/dummy-data-prod/topics.js
Labels: awaiting-review

#142 fix drag drop
  client/package-lock.json
  client/src/components/ButtonsSection/DragDrop.js
  server/package-lock.json
  server/package.json
Labels: awaiting-review

#144 remove duplicate route from the navbar
  client/src/components/Navbar/NavRoutes.js
Labels: awaiting-review

#149 fix icons
  client/src/components/TopicFormWithResources/TipInput.js
  client/src/pages/Admin/SectionForm/index.js
Labels: awaiting-review

#159 Remove common-i18n outdated dummy-data
  server/src/database/dummy-data-prod/common-i18n.js
  server/src/database/dummy-data/index.js
Labels: awaiting-review

#161 fix design bugs
  client/src/constants/resources.js
  client/src/pages/Accessibility/index.js
  client/src/pages/Admin/CustomiseResources/index.js
  client/src/validation/schemas/customise-resources.js
  server/src/database/dummy-data/organisations-resources.js
Labels: awaiting-review

#164 fix title color in the page header
  client/src/components/PageHeader/index.js
Labels: awaiting-review

#176 175 fix org dashboard links
  client/src/pages/Admin/Dashboard/DashboardLinks.js
Labels: awaiting-review

#158 fix copy bugs
  client/public/translate.json
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/constants/common.js
  client/src/constants/nav-routes.js
  client/src/constants/translations/english/index.js
  client/src/pages/OrgPublic/Home/index.js
  server/src/database/dummy-data-prod/common.js
  server/src/database/dummy-data-prod/topics.js
Labels: awaiting-review

#184 Add specific font-family to dropdown items
  client/src/components/Inputs/Dropdown/index.js
  client/src/pages/Accessibility/index.js
Labels: awaiting-review

#180 Fix rtl phone numbers
  client/src/components/StillNeedHelp/index.js
  client/src/pages/OrgPublic/MentalHeath/index.js
Labels: awaiting-review

#162 Fix navigation direction and duplicate arrow
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Layout/General/index.js
  client/src/components/Route/index.js
  client/src/components/SocialBanner/index.js
  client/src/components/TextWithIcon/index.js
  client/src/context/common.js
  client/src/helpers/use-language.js
Labels: awaiting-review

#165 Refactor aws json translate / update Sentry
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/express-app.js
  server/src/modules/section/use-cases/get-topics-by-section-id.js
  server/src/modules/translations/model/create.js
  server/src/services/error-handler/configure-sentry.js
  server/src/services/error-handler/index.js
  server/src/services/error-handler/sentry.js
  server/src/services/translation/translate-content.js
  server/src/services/translation/translation-api.js
Labels: approved

#171 169 fix copy changes
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/pages/Accessibility/index.js
  client/src/pages/Admin/EditContent/index.js
  server/src/database/dummy-data-prod/sections.js
  server/src/database/dummy-data-prod/topics.js
Labels: awaiting-review

#188 187 fix admin logo link and pending org links
  client/src/components/Language/LanguageBar/index.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/TextWithIcon/style.js
  client/src/pages/Admin/Dashboard/PendingDashboard.js
  client/src/pages/OrgPublic/Home/LandingContent.js
Labels: awaiting-review

#194 Remove isText to fix accessibility link
  client/src/components/Language/LanguageBar/index.js
Labels: awaiting-review

#192 Update common JSON
  client/src/constants/common.js
Labels: awaiting-review

#182 Change email to coldigital@hyde-housing.co.uk
  client/src/constants/nav-routes.js
  client/src/pages/Admin/Dashboard/index.js
Labels: awaiting-review

#196 fix copy
  server/src/database/dummy-data-prod/topics.js
Labels: awaiting-review

#197 Various fixes
  client/src/components/ButtonsSection/style.js
  client/src/constants/translations/english/menu-items.js
  client/src/pages/Admin/Dashboard/DashboardLinks.js
Labels: awaiting-review

#189 Edit content for Paying for housing section
  client/src/components/Inputs/Dropdown/index.js
  client/src/pages/Accessibility/index.js
  client/src/pages/Accessibility/style.js
  client/src/pages/Admin/SectionForm/index.js
  server/src/modules/section/use-cases/get-sub-sections.js
Labels: awaiting-review

#214 Update email link
  client/src/pages/Admin/Dashboard/index.js
Labels: awaiting-review

#210 Update T&C's and privacy policy
  client/src/constants/nav-routes.js
Labels: awaiting-review

#213 Add helper text to Markdown editor
  client/src/components/ButtonsSection/SingleButton.js
  client/src/components/ButtonsSection/index.js
  client/src/components/MDEditor/index.js
  client/src/components/TopicFormWithResources/TipInput.js
  client/src/pages/Admin/EditContent/ContentSection.js
  client/src/pages/Admin/EditContent/index.js
  client/src/pages/Admin/SectionForm/index.js
Labels: awaiting-review

#215 fix org/user ids bug
  client/src/pages/Admin/Customise/index.js
Labels: awaiting-review
